baseURL = "https://jankremer.eu/"
title = "Jan Kremer"
copyright = "CC0 1.0"
defaultContentLanguage = "de"
enableGitInfo = true

[params]
[params.author]
name = "Jan Kremer"
email = "mail@jankremer.eu"

[menus]

[[menus.main]]
name = "Blog"
pageRef = "/"
weight = 1

[[menus.main]]
name = "Fotos"
pageRef = "/fotos"
weight = 2

[[menus.main]]
name = "Ãœber mich"
pageRef = "/about"
weight = 3

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
[markup.highlight]
style = "github"
